project:
  render:
    - tutorial.qmd
title: 'Tutorial Week 10 Solutions: Predicting Attendance at Baseball Games'
format:
  html:
    output-file: "tutorial-week10-solutions"
    output-ext:  "html"
