project:
  render:
    - tutorial.qmd
title: 'Tutorial Week 10 Teaching Guide: Predicting Attendance at Baseball Games'
format:
  html:
    output-file: "tutorial-week10-teaching-guide"
    output-ext:  "html"
